<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buffet</name>
   <tag></tag>
   <elementGuidId>a13fcbac-68ac-467a-9e32-241e61ad90d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='choices']//div[${buff}]//div[1]//label[1]//label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='choices']//div[${buff}]//div[1]//label[1]//label[1]</value>
   </webElementProperties>
</WebElementEntity>
