<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radioBanner</name>
   <tag></tag>
   <elementGuidId>4f748135-e3e9-426e-975a-68ed851443a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='question_element']//div[@class='choice']/descendant::img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='question_element']//div[@class='choice']/descendant::img</value>
   </webElementProperties>
</WebElementEntity>
