<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VoteSelect</name>
   <tag></tag>
   <elementGuidId>e3a885cf-022f-4927-84c6-df7e8787b069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='page_body']/descendant::div[@class='question_element'][${rowNo}]/div/descendant::span[@class='checkmark'][${vote}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='page_body']/descendant::div[@class='question_element'][${rowNo}]/div/descendant::span[@class='checkmark'][${vote}]</value>
   </webElementProperties>
</WebElementEntity>
